version: '3'

services:
  long-report-generator:
    build: .
    container_name: zillmeter-long-report-generator
    ports:
      - 5000:5000
    environment:
      - AWS_SECRET_KEY=
      - AWS_ACCESS_KEY=
      - AWS_REGION=
      - AWS_S3_BUCKET=
      - AUTHENTICATION_KEY=
